knp_paginator:
  page_range: 5                      # Nombre de pages affichées dans la pagination
  default_options:
    page_name: page                # Nom du paramètre de requête pour la pagination
    sort_field_name: sort          # Nom du paramètre de requête pour le tri
    sort_direction_name: direction # Nom du paramètre de requête pour la direction de tri
    distinct: true                 # Permet de filtrer les doublons sur les paginations jointes

  template:
    pagination: 'gui/pagination/index.html.twig' # Template Twig pour la pagination